version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - cd frontend
      - npm i npm@latest -g
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build


artifacts:
  files:
    - '**/*'
  base-directory: 'frontend/build'